ontrollers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'toto'
        permanent: true
#     path: /
#     controller: App\Controller\DefaultController::index

# toto:
#     path: /toto
#     controller: App\Controller\DefaultController::toto