controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# index:
#     path: /
#     controller: App\Controller\DefaultController::index

# toto:
#     path: /toto
#     controller: App\Controller\DefaultController::toto